### ISSUE TITLE
fix thread replay visual aspects

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-agent#64]
When I replay a thread (by reopening an unfinished intake or clicking the "חזרה לשיחה" button):

1. The checked answers buttons should be colored, currently, just some of them are marked:

![תמונה](https://user-images.githubusercontent.com/3581741/70797745-c7642c00-1dad-11ea-820c-650d0be32246.png)
(an example is taken from https://github.com/hasadna/reportit-agent/issues/53)

2. The left side cards appear at once, while the middle thread replays and appears gradually. Our users would prefer to have the first (cards) behavior for both columns: just show all the aggregated info for the call at once, on both columns, and let them scroll down and review from the top.

**Comment by akariv** [comment]
I fixed the bug (will apply for new conversations).
The cards appearing immediately is not a problem as we have an issue to
show the entire chat immediately, no?

**Comment by noamoss** [comment]
@akariv 
>The cards appearing immediately is not a problem as we have an issue to

correct. 

I will leave this issue open and assigned to me for future check.

**Comment by noamoss** [comment]
@akariv 

>: and let them scroll down and review from the top.

currently the replayed thread are scrolled all the way to the bottom. The purpose is to let the agent start at the top and scroll down manually, while reading/refreshing memory with the report details.

**Comment by noamoss** [comment]
@akariv checked, was not fixed, this comment is still relevant, after checking with a new report:

https://github.com/hasadna/reportit-agent/issues/64#issuecomment-565616746

**Comment by akariv** [comment]
fixed except the scroll requirement

**Comment by noamoss** [comment]
checked on live and approved.
